#!/usr/bin/env python3
"""Generate the CP437 <-> Unicode table gfxlib2 needs for DRAW STRING.

gfxlib2's font is a 256-glyph bitmap indexed by BYTE, and gfxlib2 declares its
own character set:

    fb_gfx.h:  #define FB_GFX_GET_CHARSET() "CP437"

Verified against the built-in 8x8 font by rendering and dumping pixels:
byte 0x01 is a smiley, 0xE9 is theta, 0xDB is a full block -- CP437, not
Latin-1.

So drawing a USTRING means mapping each code unit to its CP437 byte. That has
to come from a table rather than from the C locale, which is what the existing
wstring path (gfx_print_wstr.c -> fb_wstr_ConvToA) uses: a locale-dependent
mapping would draw different glyphs on different machines, which is exactly
what USTRING exists to stop.

Writes src/gfxlib2/gfx_cp437.h. Run from the ustring project root:

    python tools/gen_cp437_table.py
"""

import os

OUT = os.path.join("fbc-master", "src", "gfxlib2", "gfx_cp437.h")


# Python's cp437 codec maps 0x00-0x1F to the C0 CONTROL characters, but the
# font holds CP437's graphic glyphs there -- byte 0x01 really is a smiley, as
# dumping the built-in 8x8 font confirms. So this range is spelled out.
C0_GRAPHICS = [
    0x0000, 0x263A, 0x263B, 0x2665, 0x2666, 0x2663, 0x2660, 0x2022,
    0x25D8, 0x25CB, 0x25D9, 0x2642, 0x2640, 0x266A, 0x266B, 0x263C,
    0x25BA, 0x25C4, 0x2195, 0x203C, 0x00B6, 0x00A7, 0x25AC, 0x21A8,
    0x2191, 0x2193, 0x2192, 0x2190, 0x221F, 0x2194, 0x25B2, 0x25BC,
]


def main():
    table = [ord(bytes([b]).decode("cp437")) for b in range(256)]
    table[0:32] = C0_GRAPHICS
    table[0x7F] = 0x2302  # house, not DEL

    # The reverse lookup assumes one byte per codepoint. If the C0 graphics ever
    # collided with the high range this would silently pick the wrong glyph.
    seen = {}
    for b, cp in enumerate(table):
        assert cp not in seen, "U+%04X is at both 0x%02X and 0x%02X" % (cp, seen[cp], b)
        seen[cp] = b

    assert table[0x01] == 0x263A, "expected a smiley at 0x01"
    assert table[0xE9] == 0x0398, "expected theta at 0xE9"
    assert table[0xDB] == 0x2588, "expected a full block at 0xDB"
    assert all(table[b] == b for b in range(0x20, 0x7F)), "ASCII must be identity"

    lines = []
    lines.append("/* CP437 <-> Unicode, GENERATED by tools/gen_cp437_table.py -- do not edit.")
    lines.append(" *")
    lines.append(" * gfxlib2's font is a 256-glyph bitmap indexed by byte, and gfxlib2 declares")
    lines.append(" * its charset as CP437 (FB_GFX_GET_CHARSET). Drawing a USTRING therefore")
    lines.append(" * means mapping each code unit to its CP437 byte.")
    lines.append(" *")
    lines.append(" * A TABLE, not the C locale. The existing wstring path converts via")
    lines.append(" * fb_wstr_ConvToA, so the same source draws different glyphs depending on the")
    lines.append(" * machine's locale. A portable string type cannot behave that way.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef __FB_GFX_CP437_H__")
    lines.append("#define __FB_GFX_CP437_H__")
    lines.append("")
    lines.append("/* CP437 byte -> Unicode codepoint. Every entry is in the BMP, so a uint16")
    lines.append("   holds it and it is directly comparable to a USTRING code unit. */")
    lines.append("static const unsigned short __fb_gfx_cp437_to_uni[256] = {")

    for row in range(0, 256, 8):
        cells = ", ".join("0x%04X" % table[row + i] for i in range(8))
        lines.append("\t%s,%s/* %02X */" % (cells, " " * 2, row))

    lines.append("};")
    lines.append("")
    lines.append("#endif /* __FB_GFX_CP437_H__ */")

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", OUT)
    path = os.path.normpath(path)
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d entries)" % (path, len(table)))


if __name__ == "__main__":
    main()
